### ISSUE TITLE
Add interesting reference: factsheet by IBM

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#106]
[J’ai une ressource supplémentaire à proposer] de Emilie Sirvent-Hien, emilie.hien@orange.com sur l'objet Q4.2 Conditions et limites d'utilisation d'un modèle.

Message de l'utilisateur : Bonjour, Vous pourriez citer également la proposition IBM avec les factsheet qui permet de documenter les modèles d'IA et informer sur les limites, cf: https://aifs360.mybluemix.net/

**Comment by bowni** [comment]
Added in PR #122 !
