### ISSUE TITLE
Add an answer to Q4.3

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#108]
Feedback sur Q4.3 Analyse et partage d'incidents (master_section id=187)
[Aucun élément de réponse ne me convient] de Daniel Bartolo, daniel.bartolo@externe.maif.fr sur l'objet Q4.3 Analyse et partage d'incidents.

Message de l'utilisateur : Il manque un élément de réponse : tritement et analyse mais pas de publication ou de partage externe sur le sujet

**Comment by bowni** [comment]
OK, je prends ce point aussi

**Comment by bowni** [comment]
Done in PR #122 !
