### ISSUE TITLE
Set an explanation to each evaluation element

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#109]
For the web platform, in order to manage the translations, the field "explanation" is marked as a "translation field". 
This leads to the fact that an explanation is required for each evaluation element to validate a language, it cannot be empty/None.

However, the evaluation element Q2.2 has no explanation in both languages. So it results in the non-validation of the languages. 
For now, a temporary solution has been implemented to do not take this field into consideration but this is much easier & more robust to add an explanation to this evaluation element, regardless the content.

**Comment by bowni** [comment]
OK @nicolas-landel I can take that one.

**Comment by bowni** [comment]
Done in PR #122 !
