### ISSUE TITLE
Review potential specific accessibility issue ?

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#115]
Exemple chatbot : accessibilité auprès d'un public non voyant ? 
Est-ce qu'il y a des spécificités dans l'IA?
Question d'inclusivité

**Comment by bowni** [comment]
L'accessibilité est un sujet capital. Cependant je ne pense pas qu'il soit spécifique à l'IA - c'est le numérique dans son ensemble qui offre des opportunités formidables et pose aussi des défis considérables du point de vue de l'accessibilité.

**Comment by bowni** [comment]
@ClementMayer je propose de clore cette issue ?
