### ISSUE TITLE
Références : The Global Landscape of AI Guidelines & Code Carbon

### ISSUE THREAD

**Issue by SaboniAmine** [SubstraFoundation/referentiel-evaluation-dsrc#116]
Récemment, 2 sujets m'ont semblé intéressants à vous partager : 

1. [The Global Landscape of AI Guidelines](https://www.nature.com/articles/s42256-019-0088-2.epdf)

Publié par Anna Jobin, qui travaille sur les dimensions sociales des systèmes algorithmiques depuis Zürich. (Elle donne également son [point de vue](https://googlewalkout.medium.com/standing-with-dr-timnit-gebru-isupporttimnit-believeblackwomen-6dadc300d382) sur le licenciement récent de Timnit Gebru, ex-directrice de la recherche sur l'éthique chez Google AI et de ses conséquences sur la discipline).

Vous pouvez trouver [des notes](https://docs.google.com/document/d/1iPwGoTPa0Gz70YUJDgXmI3oFE7IDw_8_pb9Hy56xTtM/edit?usp=sharing) sur la présentation de l'article par Anna Jobin effectuée dans le cadre du séminaire de l'ecn-EHESS "Étudier les cultures numériques" donné par Antonio Casilli, le 27 janvier dernier.

2. [Code Carbon](https://codecarbon.io/)

Le travail effectué par notamment Yoshua Bengio sur la mise en application de certains principes évoqués dans le référentiel dans l'outil [Code Carbone](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9325146). L'outil présente quelques exemples sur sa [documentation sommaire](https://mlco2.github.io/codecarbon/). Il a également été présenté à la conférence SocML202 et des notes des présentations sont disponibles [par ici](https://docs.google.com/document/d/1RgLNfJOLWOC4QJ7g3YbAVT-JxAS001_pJ3C660AFvVo/edit?usp=sharing).

**Comment by bowni** [comment]
Super @SaboniAmine, merci pour ces références et les clés de lecture qui les accompagnent. On inclut ça dans les ressources dès la prochaine release.

**Comment by bowni** [comment]
Note: _the Global Landscape of AI Guidelines_ is referenced in the _Méta-études_ section

**Comment by bowni** [comment]
Added in PR #122 !
