### ISSUE TITLE
Resource - dead link

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#118]
For the resource [Technical guide] - Privacy Enhancing Technologies Decision Tree (v2), Private AI, 2020, displayed in the Q1.7 and Q1.8, the link is dead and there is a 404 issue.

So either find the new link and remove this resource.

Note that I created an issue for the platform to report automatically the "dead link", which can unfortunately happen often.

**Comment by bowni** [comment]
Found the new link! http://www.private-ai.ca/PETs_Decision_Tree.svg

**Comment by nicolas-landel** [comment]
Yes top, en fait ils n'ont juste plus leur certificat donc peut être que ça va revenir ?

**Comment by bowni** [comment]
Done in PR #122 !
