### ISSUE TITLE
Missing blank lines between section titles and keywords

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#119]
For the sections 1 and 2 of the English markdown assessment, there is a missing `\n` between the section title and the keyword in the raw file - but it is correctly displayed in markdown file.

`### Section 1 - Protecting personal or confidential data
**[Data privacy]**`

should be: 

`### Section 1 - Protecting personal or confidential data

**[Data privacy]**`

**Comment by nicolas-landel** [comment]
Note that this currently not a pb as I did a fix on the jsonify project to cope with the fact that there may be only one line break '\n' between the section title and the keyword.

**Comment by bowni** [comment]
Done in PR #122 !
