### ISSUE TITLE
AI registers

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#123]
Check how to integrate AI registers:
https://towardsdatascience.com/ai-registers-finally-a-tool-to-increase-transparency-in-ai-ml-f5694b1e317d

**Comment by SaboniAmine** [comment]
Référence super intéressante.
Cela pourrait s'intégrer dans la partie 5.5 (Transparence), ce genre de registre pourrait typiquement intégrer des outils d'outils descriptifs comme Code Carbon (qui est plutôt sur le point 6.1) ou les model cards de [Google](https://modelcards.withgoogle.com/face-detection) ou [Salesforce](https://blog.einstein.ai/model-cards-for-ai-model-transparency/)

**Comment by bowni** [comment]
See PR #145
