### ISSUE TITLE
Study the new EU proposal for a Regulation laying down harmonised rules on artificial intelligence (Artificial Intelligence Act)

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#138]
Study the new proposal EU [proposal for a Regulation laying down harmonised rules on artificial intelligence (Artificial Intelligence Act)](https://digital-strategy.ec.europa.eu/en/library/proposal-regulation-laying-down-harmonised-rules-artificial-intelligence-artificial-intelligence) and identify potential new elements.

**Comment by j-abi** [comment]
On first reading, I really like this sentence for us
> The development of AI systems other than high-risk AI systems in accordance with the requirements of this Regulation may lead to a larger uptake of trustworthy artificial intelligence in the Union. Providers of non-high-risk AI systems should be encouraged to create codes of conduct intended to foster the voluntary application of the mandatory requirements applicable to high-risk AI systems.

But let's study this further, of course.

**Comment by bowni** [comment]
From this @j-abi I think we should list the *mandatory requirements applicable to high-risk AI systems* and see how they fit with the referential/assessment.
