### ISSUE TITLE
Add Counterfit to resources on ML security

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/referentiel-evaluation-dsrc#144]

**Comment by bowni** [comment]
@HeytemBou could you please provide the references you identified in the newsletters you monitor? Thanks

**Comment by bowni** [comment]
Added in PR #145 as a key reference to 1.7 and 1.8

**Comment by HeytemBou** [comment]
Link to the article: https://www.microsoft.com/security/blog/2021/05/03/ai-security-risk-assessment-using-counterfit/
Link to Github repo: https://github.com/Azure/counterfit/
