### ISSUE TITLE
Mesures sur le partage de valeur entre partie-prenante

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#33]
Je me demande dans quelle mesure il ne faudrait pas intégrer des mesures en lien avec les notions de répartition de la création de valeur de la mise en place d'un modèle entre les différents acteurs. Cela me parait une composante importante d'une Data Science Responsable.

**Comment by bowni** [comment]
Dans le cas de figure où la chaîne de valeur comprend plusieurs acteurs (Q5.1) et où il y a activité économique associée, en effet c'est quelque chose qui manque aujourd'hui. Je crois qu'on avait évoqué un tout petit peu le sujet au 1er atelier ou avant d'ailleurs et qu'on l'avait mis de côté. Très intéressant à réintroduire, je m'en charge.
