### ISSUE TITLE
Data science en temps de crise

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#34]
En période de crise comme celle du CoVid-19, des questions se posent sur l'utilisation des données lorsqu'un arbitrage entre confidentialité et "sauver des vies" doit être fait. 
Est-ce que certaines mesures sur des circonstances exceptionnelles ne pourraient pas être décrites ?

**Comment by bowni** [comment]
On pourrait imaginer atténuer le poids des éléments d'évaluation sur les données personnelles et confidentielles. Mais à la réflexion cela me semble délicat à introduire dans un tel référentiel d'évaluation. C'est en fait prévu par les textes réglementaires, par exemple dans le RGPD une disposition permet aux Etats de le suspendre en cas de force majeure ou quelque chose dans ce genre. Je serais plus confortable de laisser les circonstances exceptionnelles en dehors de l'évaluation.

**Comment by bowni** [comment]
@ClementMayer peut-on clore l'issue ou veux-tu pousser la réflexion plus loin ?
