### ISSUE TITLE
Modalité de scoring de l'évaluation - cas des domaines "non concernés"

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/referentiel-evaluation-dsrc#38]
La question de comment scorer les différents éléments de l'évaluation n'est pas évidente. Un premier essai peut être consulté [ici](https://docs.google.com/spreadsheets/d/1QhvOTsPpNhNcLlt7z_-vL3EBCRAxhjrhy_ybYKcDuFM/edit?usp=sharing). Un point particulièrement délicat est la prise en compte des cas où une organisation n'est pas concernée par une ou plusieurs questions de l'évaluation.

Prenons un exemple pour accompagner le raisonnement. Imaginons une organisation qui n'est pas concernée par les environnements thématiques où il y a des risques de discrimination à l'encontre de certains groupes sociaux, et que l'ensemble des éléments d'évaluation sur ce sujet correspondent à un total de `4` points sur `50`.

- Dans le cas de figure où l'organisation n'est pas sujette aux risques correspondants aux sujets par lesquels elle n'est pas concernée, il est important que la réponse "non concerné" ne soit pas pénalisante pour elle. Au contraire il est nécessaire que le scoring associé souligne que le fait de n'être pas sujet à un risque est positif dans la perspective d'une activité _responsable et de confiance_. Dans notre exemple, l'activité data science de l'organisation ne présente pas le risque de générer des biais discriminatoires.
- Pour autant, peut-on attribuer automatiquement l'ensemble des `4` points maximaux correspondant aux questions par lesquelles l'organisation n'est pas concernée ? C'est une option possible. L'inconvénient est que les organisations avec une toute petite activité data science très peu exposée (pas de risques de discriminations, pas de données personnelles, pas de modèles en production, etc.) obtiendraient quasi automatiquement un score de départ élevé. Ca ne serait pas illogique, mais ça ne serait pas non plus complètement représentatif.
- Une seconde option serait de ne pas compter de point sur les sujets où une organisation est "non concernée", et de dilater tous les sujets qui restent pour que le total maximal atteignable soit le même. Dans notre exemple on dilaterait tous les éléments d'évaluation restant d'un facteur `50/46`
- Une troisième voie serait de combiner les 2 mécanismes : la moitié des points du sujet non concerné va à l'organisation (`2` points dans l'exemple), et les autres sujets sont dilatés d'autant (d'un facteur `50/48`). Ainsi :
  - le score maximal atteignable reste le même pour toutes les organisations (`50` points), concernées ou non concernées par différents sujets
  - lorsqu'une organisation est non concernée par un sujet, et donc non sujette au risque sous-jacent, cela est valorisé par la moitié des points correspondants
  - les organisations concernées par peu de sujets n'ont pas automatiquement un score de départ trop élevé, et doivent donc faire la preuve de leurs efforts pour obtenir un bon score

Qu'en pensez-vous ?

**Comment by ClementMayer** [comment]
Mon point de vu personnel : 
- J'aime beaucoup la dernière approche proposée 
- Est-ce qu'il vaudrait mieux pas un score sur 100 au global qui est plus lisible ? (ou alors, si on veut être facétieux, sur 42...)

**Comment by bowni** [comment]
This was presented at the 4th workshop and made consensus. We now close this issue!
