### ISSUE TITLE
Ajouter le serment d'Hippocrate de dataforgood

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/referentiel-evaluation-dsrc#45]

**Comment by ClementMayer** [comment]
Il est déjà présent : 
https://github.com/SubstraFoundation/referentiel-evaluation-dsrc/blob/master/references.md#d%C3%A9clarations-chartes-serments
MAis en effet faut peut être changer le lien.

**Comment by bowni** [comment]
Des aspects intéressants sur lesquels réfléchir et peut-être ajouter des éléments :

> ... veiller à ce que le responsable du système puisse autant que possible fournir une explication des résultats du modèle algorithmique aux personnes concernées et ce d’autant plus s’il est légalement tenu d’expliquer ces décisions.
> 
> Le droit oblige à pouvoir expliquer le fonctionnement des algorithmes. Lire moins
> L'article 22 du Règlement Général sur la Protection des Données (RGPD) prévoit un principe selon lequel la personne concernée a le droit de s’opposer à ce qu’une décision sur elle soit prise uniquement sur le fondement d’un traitement automatisé. Certaines exceptions sont toutefois aménagées et le Règlement oblige à prendre des mesures appropriées pour protéger les personnes lorsqu’elles font l’objet d’une décision uniquement fondée sur un traitement automatisé.
> 
> L’article 10 de la loi française distingue deux cas :
> 
> ⁃ Dans le secteur privé, lorsqu’une décision est prise uniquement sur le fondement d’un traitement automatisé, l’auteur doit pouvoir expliquer les règles définissant le traitement et les caractéristiques de sa mise en oeuvre (sauf si cette explication est couverte par un secret).
> 
> ⁃ Dans le secteur public, l’individu doit être informé que la décision a été fondée uniquement sur un algorithme et l’auteur de la décision doit pouvoir expliquer les règles définissant le traitement et les caractéristiques de sa mise en oeuvre.
> 
> La décision du Conseil Constitutionnel du 12 juin 2018 précise dans quelles conditions les administrations peuvent avoir recours à des algorithmes pour prendre des décisions concernant les individus.
> ... mesurer le biais et la variance pour contrôler l'exactitude et la dispersion du résultat et documenter les métriques d'erreur retenues.
> 
> ... déterminer le meilleur compromis entre la performance et l'interprétabilité sur l’ensemble des modèles à disposition et autant que possible, opter pour les modèles les plus simples à expliquer aux personnes concernées (un modèle performant permettra de diminuer les risques d’erreur tandis qu’un modèle interprétable permettra de mieux justifier les résultats du modèle).
>
