### ISSUE TITLE
Interprétabilité des modèles - référence

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#48]
Très bon site qui permet d'expliquer l'interprétabilité des modèles de ML et pourquoi c'est important
https://christophm.github.io/interpretable-ml-book/

def de interprétabilité : 1) le niveau de compréhension d'un humain quant aux raisons d'une décision
2) La capacité d'un humain à reproduire de manière constante les résultats d'un modèle

Ce document évoque notamment la valeur de shapley pour étudier la contribution d'une feature à un modèle et lui donner son importance (regarder si lien éventuellement avec la contributivité)

**Comment by nicolas-landel** [comment]
repo github : https://github.com/christophM/interpretable-ml-book

**Comment by bowni** [comment]
Super référence, bien vu @nicolas-landel . Je prends l'action je vais l'ajouter
