### ISSUE TITLE
Ajouter scrambling et distillation de modèles (cf. travaux HealthChain)

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/referentiel-evaluation-dsrc#49]
- Data scrambling : papier (non accepté en 1ère soumission)
- Distillation pour compression
- Distillation anonymisante (differentially-private)

**Comment by bowni** [comment]
@RomainGoussault @mattthieu quelles ressources recommandez-vous sur ces sujets ?

**Comment by RomainGoussault** [comment]
https://arxiv.org/pdf/1503.02531.pdf
https://towardsdatascience.com/knowledge-distillation-simplified-dd4973dbc764
