### ISSUE TITLE
Translate the assessment from FR to EN

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/referentiel-evaluation-dsrc#53]

**Comment by nicolas-landel** [comment]
I can help on this topic if you want. Even if my English is not perfect, I can do a first draft. I will just need to have a clear vision of the process : create a new branch and work on the files' tanslation on it. Is the goal to replace the French files by English ones in the repo ? or to have both present in the repository ?

**Comment by ClementMayer** [comment]
The goal is to have both in the repo. So you need to create a new branch and create a new file assessment.

**Comment by ClementMayer** [comment]
A branch has been created: https://github.com/SubstraFoundation/referentiel-evaluation-dsrc/pull/62
