### ISSUE TITLE
Open question - Explanation of technical terms

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#56]
As I was reading the referential, some terms I didn't know the meaning were part of an element of evaluation. That implies to search for their definitions. It may be interesting that the technical terms are explained in the element of evaluation. Here I refer to the questions Q3.6 (seuils de classification) and Q3.7 (interpretabilité et explicabilité). There is no explanation for these elements of evaluation. 

I think this point implies a larger one : to who the evaluation is intended to ? If it's ML professionals, it can be ok to skip to much explanation. But it can be interesting to have a wilder spectrum and may be to raise awarness of young ML developers or students about these topics. But this will require to go further into the explanation of terms ( and may be more than just links to resources).

**Comment by bowni** [comment]
> As I was reading the referential, some terms I didn't know the meaning were part of an element of evaluation. That implies to search for their definitions. It may be interesting that the technical terms are explained in the element of evaluation. Here I refer to the questions Q3.6 (seuils de classification) and Q3.7 (interpretabilité et explicabilité). There is no explanation for these elements of evaluation.

Ok, noted for Q3.6 and Q3.7, I'll make sure there is (a link to) a definition in the description or the explanation.


> I think this point implies a larger one : to who the evaluation is intended to ? If it's ML professionals, it can be ok to skip to much explanation. But it can be interesting to have a wilder spectrum and may be to raise awarness of young ML developers or students about these topics. But this will require to go further into the explanation of terms ( and may be more than just links to resources).

It is indeed professionals, data science practitioners. Too much definitions or general public wordings might weaken the assessment in making it not serious / professional enough for specialists. We have to find the right balance.
