### ISSUE TITLE
Monitoring of ML system - Q3.5

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#57]
May be we can add another choice for the question (Dans les cas de figure où des modèles prédictifs élaborés par votre organisation sont utilisés dans des systèmes en production ) to indroduce the notion of "continuous" monitoring with the implementation of dashboards and alerts. Currently, all the choices concern the fact that people are responsible of the monitoring, whereas tools exist for it.

It could be something like "Des outils de monitoring permettent une surveillances continue des système de ML et peuvent déclencher des alertes directement auprès de l'équipe responsable"

**Comment by nicolas-landel** [comment]
With may be as resource this article : https://christophergs.com/machine%20learning/2020/03/14/how-to-monitor-machine-learning-models/#spectrum

**Comment by bowni** [comment]
Good suggestion, I'll look into it and see how to improve Q3.5.

**Comment by bowni** [comment]
Actually this would best fit in Q6.1 and Q6.2, in the section about the usage of ML models in production. Section 3 and Q3.5 are about the validity of the performance score, more from a performance evaluation point of view.
