### ISSUE TITLE
Information sent to the users

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#58]
Add in the referential, may be a new element of evaluation to deal with the fact that the user need to be informed that he is using an AI and that there are x possible classifications/results.

It could be interesting to study deeper the interpretability of AI. For example an evaluation element which asks whether the user is informed of the reasons of a specific classification (and what changes could lead to a change in the classification : counterfactual explanation).

**Comment by bowni** [comment]
This is an important aspect that the assessment doesn't cover as of now. I am on it then!
