### ISSUE TITLE
Réflexion sur la mise en place d'un scoring par section

### ISSUE THREAD

**Issue by ClementMayer** [SubstraFoundation/referentiel-evaluation-dsrc#69]
Comment mettre en place un scoring cohérent par section ? 
Lors de l'atelier n°4, certains participants ont exprimé le souhait de pouvoir voir les domaines où ils ont besoin de renforcement.

**Comment by ClementMayer** [comment]
Cela permettrait également de faire des retours / fournir des ressources pour les sections moins bien notées

**Comment by nicolas-landel** [comment]
On pourra implementer un scoring par section dans l'application, cela ne devrait pas poser de problème particulier !

**Comment by ClementMayer** [comment]
Techniquement ce n'est pas compliqué mais d'un point de vue du référentiel, il faut quand même s'interroger sur ce que signifier avoir un score par section : si tu as seulement trois questions dans ta section, et deux qui ne sont pas applicables, c'est compliqué de se dire que le score à un sens. 
C'est plus dans cette optique là que nous devons pousser la réflexion.

**Comment by nicolas-landel** [comment]
Hello, I just realized the evaluation in order to obtain the max score and I got the score for each section. There is a not high disparity between the sections (4 sections near to the mean: 10,8) but just the 2nd section has a too low score and the 5th has a too high score.

**Comment by bowni** [comment]
@nicolas-landel @ClementMayer this is now done, right? I let you close this issue.

**Comment by ClementMayer** [comment]
It has been done and will be available soon online
