### ISSUE TITLE
Article which evaluates the AI ethics guidelines 

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#78]
https://link.springer.com/content/pdf/10.1007/s11023-020-09517-8.pdf

**Comment by nicolas-landel** [comment]
Among the top rated guidelines, there is Beijings AI guidelines : https://www.baai.ac.cn/news/beijing-ai-principles-en.html

**Comment by bowni** [comment]
Well spotted @nicolas-landel. If I remember correctly this is not the first meta-study on AI ethics guidelines. We should probably create a dedicated section to flag them: it would make it easier for enthusiastic readers to compare them and extract precious findings.
