### ISSUE TITLE
Change how the conditions inter elements is written

### ISSUE THREAD

**Issue by nicolas-landel** [SubstraFoundation/referentiel-evaluation-dsrc#79]
Currently multiple way it is written : (Condition : R1.5 <> 1ère réponse); (Condition : R2.2 = Concerné)

Always write this way : (Condition : R**section_id**.**element_id** <> **choice_id**) 
for example : (Condition : R1.5 <> a) 
(Condition : R2.2 <> b)

**Comment by bowni** [comment]
@nicolas-landel is this issue still valid? Should I work on it just now?
