### ISSUE TITLE
Add HRX's article into the "various controversies" section

### ISSUE THREAD

**Issue by meuce** [SubstraFoundation/referentiel-evaluation-dsrc#99]
Article about a combinaison of some bias and human rights non conformities regarding the construction and use of the CONARC database and the Facial Recognition System for Fugitives in Buenos Aires:

https://www.hrw.org/news/2020/10/09/argentina-child-suspects-private-data-published-online

**Comment by bowni** [comment]
Just edited the link to remove unecessary tracking variables.

**Comment by bowni** [comment]
Added in PR #122 !
